name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Install clojure deps
        uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.3

      - name: Cache maven
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: m2-${{ hashFiles('deps.edn') }}
          restore-keys: |
            m2-

      - name: Test
        run: clj -M:test
